### ISSUE TITLE
Let's go to 21st century

### ISSUE THREAD

**Issue by netbull** [nikolay-kolev97/online-shop#11]
Now.. using public CDN for loading external assets /js or css libs/ is fine, but let's go to 21st century and implement some really awesome stuff.

- You can start learning about [webpack](https://webpack.js.org/). This is a "bundler" which means it takes your source files and bundles them. During this "bundling" you can configure it to do a lot of cool stuff like when you build your production bundle to minify the css and js, to optimise the images etc. Pretty much in modern times it's a must to use such thing as webpack /there are also other alternatives/.

- Read more about [S(a|c)ss](https://sass-lang.com/guide). This is.. you can think of it as CSS on steroids. It's really cool stuff. If you use Scss the syntax is almost like the CSS, but it supports variables, functions and etc. With variables you can define for example a color and then you this variable all over you other files. Then you want to change this color, you need to change only the value of this variable, not all css files. another example is if you need to use a shade of a color. In that case you use a function to darken or lighten the given color hex code specifying change in percents. Again awesome stuff!

Of course in order to work with all this you will need [Node.js](https://nodejs.org/en/) installed locally on your machine and [Yarn](https://yarnpkg.com/getting-started/install)

**Comment by nikolay-kolev97** [comment]
Okey,thank you, In the moment I am learning more for Node.js and how to install his packets in command promt and how to make web server and how it works in theoretically and practically. That is important for my diploma too. In last weeks I went fundametal things about javascript to understand the code.

**Comment by netbull** [comment]
For webserver DO NOT install anything locally! Use [Docker](https://www.docker.com/).

Get familiar with Docker and start using it.

If you need assistance or questions you can always write here.

**Comment by nikolay-kolev97** [comment]
Okay, I read the tutorial of webpack and I need from more practice now,  to see how much I understood it. Can you give me some exercise with webpack?
I also understood the consept of the Node.js technology.

**Comment by nikolay-kolev97** [comment]
I read Scss too. It is really cool technology.
