### ISSUE TITLE
Change assets paths

### ISSUE THREAD

**Issue by netbull** [nikolay-kolev97/online-shop#2]
The assets paths should be relative in order to load properly on different environments/machines.

**Comment by nikolay-kolev97** [comment]
I made the assets path to be relative.

> The assets paths should be relative in order to load properly on different environments/machines.

I made the assets path to be relative.

**Comment by netbull** [comment]
Not really :) correct the paths in all files, no only in index.html

**Comment by nikolay-kolev97** [comment]
Sorry :) , now I think it is better
