### ISSUE TITLE
Draw a sketch

### ISSUE THREAD

**Issue by netbull** [nikolay-kolev97/online-shop#6]
This is the initial step of the project.

Don't lose time in the details, it's just a sketch after all.

**Comment by nikolay-kolev97** [comment]
![148744940_257113222685867_4071394992482064426_n](https://user-images.githubusercontent.com/73642360/107631645-00c45000-6c6e-11eb-93d0-0cbf3bd451e1.jpg)
That is my sketch about my online shop.

**Comment by netbull** [comment]
![107631645-00c45000-6c6e-11eb-93d0-0cbf3bd451e1](https://user-images.githubusercontent.com/2797954/107634591-703c3e80-6c72-11eb-8af9-1f08fc5146af.jpg)

**Comment by nikolay-kolev97** [comment]
![149858141_3959301970840637_5644485728233101696_n](https://user-images.githubusercontent.com/73642360/107636829-e42c1600-6c75-11eb-8444-cd4c142ce1e8.jpg)

**Comment by netbull** [comment]
Any search? shopping cart?

**Comment by nikolay-kolev97** [comment]
![149242992_838241883401242_3351509368818662735_n](https://user-images.githubusercontent.com/73642360/107645667-a3d29500-6c81-11eb-97d0-5b8f409b2703.jpg)

**Comment by netbull** [comment]
Good, moving on..
