### ISSUE TITLE
Create a Mockup

### ISSUE THREAD

**Issue by netbull** [nikolay-kolev97/online-shop#7]
Transform your sketch from #6 into a living Mockup.

*Mockup is basic html page with the elements which you drew into the sketch and a bit of CSS. Basically it's just a prototype of the sketch which you can "touch" and play with.

**Comment by nikolay-kolev97** [comment]
I created a basic html page and changed the document in the repository online-shop.

**Comment by netbull** [comment]
Don't forget to close the issues when you finish them.. if it's needed they will be reopened.

**Comment by nikolay-kolev97** [comment]
Okey, sorry.
